#define Tk                                       0x1000
#define X_cursor                                 0x1001
#define arrow                                    0x1002
#define based_arrow_down                         0x1003
#define based_arrow_up                           0x1004
#define boat                                     0x1005
#define bogosity                                 0x1006
#define bottom_left_corner                       0x1007
#define bottom_right_corner                      0x1008
#define bottom_side                              0x1009
#define bottom_tee                               0x100A
#define box_spiral                               0x100B
#define center_ptr                               0x100C
#define circle                                   0x100D
#define clock                                    0x100E
#define coffee_mug                               0x100F
#define cross                                    0x1010
#define cross_reverse                            0x1011
#define crosshair                                0x1012
#define diamond_cross                            0x1013
#define dot                                      0x1014
#define dotbox                                   0x1015
#define double_arrow                             0x1016
#define draft_large                              0x1017
#define draft_small                              0x1018
#define draped_box                               0x1019
#define exchange                                 0x101A
#define fleur                                    0x101B
#define gobbler                                  0x101C
#define gumby                                    0x101D
#define hand1                                    0x101E
#define hand2                                    0x101F
#define heart                                    0x1020
#define xicon                                    0x1021
#define iron_cross                               0x1022
#define left_ptr                                 0x1023
#define left_side                                0x1024
#define left_tee                                 0x1025
#define leftbutton                               0x1026
#define ll_angle                                 0x1027
#define lr_angle                                 0x1028
#define man                                      0x1029
#define middlebutton                             0x102A
#define mouse                                    0x102B
#define pencil                                   0x102C
#define pirate                                   0x102D
#define plus                                     0x102E
#define question_arrow                           0x102F
#define right_ptr                                0x1030
#define right_side                               0x1031
#define right_tee                                0x1032
#define rightbutton                              0x1033
#define rtl_logo                                 0x1034
#define sailboat                                 0x1035
#define sb_down_arrow                            0x1036
#define sb_h_double_arrow                        0x1037
#define sb_left_arrow                            0x1038
#define sb_right_arrow                           0x1039
#define sb_up_arrow                              0x103A
#define sb_v_double_arrow                        0x103B
#define shuttle                                  0x103C
#define sizing                                   0x103D
#define spider                                   0x103E
#define spraycan                                 0x103F
#define star                                     0x1040
#define target                                   0x1041
#define tcross                                   0x1042
#define top_left_arrow                           0x1043
#define top_left_corner                          0x1044
#define top_right_corner                         0x1045
#define top_side                                 0x1046
#define top_tee                                  0x1047
#define trek                                     0x1048
#define ul_angle                                 0x1049
#define umbrella                                 0x104A
#define ur_angle                                 0x104B
#define watch                                    0x104C
#define xterm                                    0x104D
